version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
        environment:
          STAGE_IMAGE: gcr.io/unicorn-attack/goapi
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run: docker build -t ${STAGE_IMAGE}:$CIRCLE_SHA1 .
